# Docker Compose
# https://docs.docker.com/compose/
# Usage: docker-compose up

version: '3'
services:

  app:
    restart: always
    image: ansible-role-python
    environment: &environment
      - ENVIRONMENT=local
    build:
      context: .
      dockerfile: provision/docker/app/Dockerfile
    volumes:
      - .:/usr/src
    env_file:
      - .env
