---
- name: Check virtualenv created
  stat:
    path: "{{ python_pyenv_path }}/.pyenvrc"
  register: _python_virtualenvs_exist
  tags:
    - virtualenvs
    - check

- name: Delete virtual environments
  shell: . {{ python_pyenv_path }}/.pyenvrc && pyenv virtualenv-delete --force {{ item.venv_name }}
         removes="{{ python_pyenv_path }}/versions/{{ item.venv_name }}/bin/python"
  with_items: "{{ python_pyenv_delete_virtualenvs | default({}) }}"
  become: true
  become_user: "{{python_pyenv_owner}}"
  ignore_errors: True
  when:
    - python_pyenv_delete_virtualenvs is defined
    - _python_virtualenvs_exist.stat.islnk is defined
