---

- name: Added Environment .bashrc
  lineinfile: dest="~/.bashrc"
              regexp="\.environmentrc"
              line="source {{ _python_path_file_environmentrc }}"
              state=present
  become: true
  become_user: "{{ python_pyenv_owner }}"

- name: Modify .bashrc
  lineinfile: dest="~/.bashrc"
              regexp="\.pyenvrc$"
              line="source {{ python_pyenv_path }}/.pyenvrc"
              state=present
  become: true
  become_user: "{{ python_pyenv_owner }}"
