# Docker Compose
# https://docs.docker.com/compose/
#
# Usage: test up
version: '3'
services:

  app:
    restart: always
    image: ansible-role-python
    environment: &environment
      - DEBUG=True
    build:
      context: .
      dockerfile: provision/docker/app/Dockerfile
    env_file:
      - .env
